 # Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OneBAuction' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for OneBAuction
    
    #3D滚动视图控件
    pod 'iCarousel', '~> 1.8.3'
    #ActionSheet控件
    pod 'FSActionSheet', '~> 1.0.1'
    
    #丰富的分类工具库
    pod 'YYCategories', '~> 1.0.4'
    
    #提供数据模型转换
    pod 'YYModel', '~> 1.0.4'
    
    #键盘管理工具
    pod 'IQKeyboardManager', '~> 6.0.3'
    
    #上拉加载，下拉刷新
    pod 'MJRefresh', '~> 3.1.15.3'
    
    #网络图片加载工具
    pod 'SDWebImage', '~> 4.3.3'
    
    #进度条
    pod 'SVProgressHUD', '~> 2.2.5'
    
    #AutoLayout工具
    pod 'Masonry', '~> 1.1.0'
    
    #Alert工具
    pod 'SCLAlertView-Objective-C', '~> 1.1.3'
    
    #网络请求
    pod 'AFNetworking'
    #轮播图
    pod 'SDCycleScrollView'
    
    target 'OneBAuctionTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

